import Head from "next/head";
import Graph from "../Components/Graph"
import Data from "./Data"
import { useEffect, useState } from "react";
import Select from 'react-select';

const Home = () => {

  const studentNames = [...new Set(Data.map((student) => student.name))]
  studentNames.unshift("All")

  const [selected, setSelected] = useState("All")
  const [radio, setRadio] = useState("both")
  const [filteredAssignment, setFilteredAssignment] = useState([])
  
  function filterData(Data){
    const assignmentData = Object.values(Data.reduce((acc, {assignment, difficulty, fun}) => { 
      acc[assignment] = acc[assignment] || { assignment, difficulty: 0, fun: 0};
      acc[assignment].difficulty += difficulty;
      acc[assignment].fun += fun;
      return acc;
    }, []))

    setFilteredAssignment(assignmentData)
    return assignmentData
  }

  useEffect(() => {
    if(selected.value === "All") {
      const res = filterData(Data)
      filterData(res.map((assignment) => ({
        assignment: assignment.assignment,
        difficulty: assignment.difficulty / 10,
        fun: assignment.fun / 10,
      })))

      return
    }
    filterData(Data.filter((student) => student.name === selected.value))
  }, [selected])  

  const onFilterChange = (e) => {
    setRadio(e.target.value)
  }

  return (
    <>
      <Head>
        <title>React Student Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-h-screen text-center items-center">

        <h1 className="py-6 text-6xl text-black font-semibold">React Student Dashboard</h1>

        <Select
        className="py-6" 
        defaultValue={selected}
        onChange={setSelected}
        options={studentNames.map((name) => ({value: name, label: name}))}
        />
        <div className="flex gap-2 font-semibold">
          <input type="radio" value="both" checked={radio === "both"} onChange={onFilterChange}/>
          <label>both</label>
          <input type="radio" value="diff" checked={radio === "diff"} onChange={onFilterChange}/>
          <label>diff</label>
          <input type="radio" value="fun" checked={radio === "fun"} onChange={onFilterChange}/>
          <label>fun</label> 
        </div>

        <Graph assignmentData={filteredAssignment} filter={radio}/>
      </main>
    </>
  );
};

export default Home;
